[build]
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  # Exclure les routes API Astro du redirect
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = false

[[redirects]]
  # Redirection de l'ancien slug vers le nouveau
  from = "/prevente-felicitation"
  to = "/100k-felicitations"
  status = 301
  force = true

[functions]
  directory = "netlify/functions"